version: "3"
services:


  reservation:
    container_name: reservation
    build: ./Reservation
    ports:
      - "8556:8556"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka


  camping:
    container_name: camping
    build: ./Camping
    ports:
      - "8084:8084"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka

  discovery:
    build: ./EurekaServer
    ports:
      - "8761:8761"
    image: "discovery-service"

  apigateway:
    container_name: apigateway
    build: ./Apigetway
    ports:
      - "8089:8089"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    depends_on:
      - discovery