spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceOffrePlat
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: offreplat

server:
  port: 8555

